version: '2'
distribution_spec:
  description: Llama Stack with Ollama inference for local development
  providers:
    inference:
    - provider_type: remote::ollama
    safety:
    - provider_type: inline::llama-guard
    agents:
    - provider_type: inline::meta-reference
    vector_io:
    - provider_type: inline::faiss
    datasetio:
    - provider_type: inline::localfs
    scoring:
    - provider_type: inline::basic
    eval:
    - provider_type: inline::meta-reference
    post_training:
    - provider_type: inline::torchtune-cpu
    tool_runtime:
    - provider_type: inline::rag-runtime
    telemetry:
    - provider_type: inline::meta-reference
    files:
    - provider_type: inline::localfs
image_type: venv
